version: '3.3'
services:
  postgresql:
    image: postgres:15
    container_name: link-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=scrapper
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=postgres
      - --password=password
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      backend:
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: "tinkoff"
      RABBITMQ_DEFAULT_PASS: "rabbit"

networks:
  backend:

volumes:
  db:
    driver: local
