app:
  test: 14
  scheduler:
    interval: PT010S
  database-access-type: jpa
  rabbitData:
    username: tinkoff
    password: rabbit
    exchange: linkExchange
    queue:  changeLink
    root:   updateLink
  useQueue: true

springdoc:
  swagger-ui:
    path: /swagger-ui

bot:
  host: http://localhost:8082/

stackoverflow:
  url: https://api.stackexchange.com/2.3

github:
  url: https://api.github.com

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    password: password
    username: postgres
  jpa:
    show-sql: true