app:
  test: 12
  rabbitData:
    username: tinkoff
    password: rabbit
    queue: changeLink

bot:
  token: ${telegram.api.token}

scrapper:
  host: http://localhost:8080/

server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui
