name: Tinkoff Application Bot CI with Maven

on:
  push:
    paths:
      - './bot'
    branches: [ "main", "hw9" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build project with Maven
        run: mvn package -pl bot -am

      - name: See jar file
        run: ls -la bot/target

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: ./bot/target/bot-1.0-SNAPSHOT.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./bot
          file: ./bot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bot-app:latest