name: Tinkoff Application Scrapper CI with Maven

on:
  push:
    paths:
      - './bot'
    branches: ["main", "hw9"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build project with Maven
        run: mvn package -pl scrapper -am